mutation {
  createAppUser(data: 
    {
      email: "demotester1@email.cz", 
     	nickname: "tester2",
      password: "aplikace2022" 
    }) 
  {
    status
  }
}

# puts a user in a group, sets role
mutation {
    createUpdateAppUser (data:{id:5, appUserGroupId: 2, appUserRoleId: 2}) {
      result
    }
}

#creates
mutation {
  createUpdatePerson(data: { name: "Adam", surname: "Pospisil", appUserGroupId: 1 }) {
    partyId
  }
}

# updates
mutation {
  createUpdatePerson(data: { partyId: 3, name: "Karel", surname: "Pospisil", appUserGroupId: 1 }) {
    partyId
  }
}

mutation {
  createUpdatePartyRelationship(
    data: { firstPartyId: 5, secondPartyId: 4, typeId: 1, operation: "CREATE" }
  ) {
    id
  }
}

mutation {
  createUpdatePartyRelationship(
    data: { firstPartyId: 2, secondPartyId: 3, typeId: 1, id:4, operation: "UPDATE" }
  ) {
    id
  }
}

#creates
mutation {
  createUpdateOrganization(data: { name: "CSOB", appUserGroupId: 1 }) {
    partyId
  }
}

mutation {
    createUpdateNote (data:{content: "tajna", noteTarget: "party", noteTargetId: 1, isPrivate:  true})  {
   result
    message
    }
  }

#updates
mutation {
    createUpdateTag (data:{id:1, name: "móda 2022", partyId: 2})  {
   result
    message
    }
  }

#creates
mutation {
    createUpdateContact (data:{mainPartyId: 1, value: "+420777000111", typeId: 1, operation: "CREATE"})  {
   id
    value
    }
  }
